easy_admin:
    entities:
        Infos:
            class: App\Entity\Infos
        Project:
            class: App\Entity\Project
            new:
                fields:
                    - {property: 'Title'}
                    - {property: 'content'}
                    - {property: 'link'}
                    - {property: 'img', type: 'file'}
        Blog:
            class: App\Entity\Blog
        Skills:
            class: App\Entity\Skills
            new:
                fields:
                    - {property: 'content'}
                    - {property: 'level'}
                    - {property: 'img', type: 'file'}
                edit:
                    - {property: 'content'}
                    - {property: 'level'}
                    - {property: 'img', type: 'file'}

